# Generated by Django 3.2.9 on 2021-11-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.TextField(max_length=25)),
                ('name', models.TextField(max_length=100)),
                ('number', models.IntegerField()),
                ('status', models.TextField(max_length=100)),
                ('auth_number', models.TextField(max_length=25)),
                ('code_control', models.TextField(max_length=25)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
