# Generated by Django 3.2.9 on 2021-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
