# Generated by Django 3.2.9 on 2021-11-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.booking'),
        ),
    ]
